x-environment_file: &environment_file
  env_file:
    - ".env"

services:
  transcriber_server:
    container_name: transcriber_server
    build:
      context: transcriber/
      dockerfile: Dockerfile
    <<: *environment_file
    ports:
      - "8002:8002"
  nlp_tools:
    container_name: nlp_tools
    <<: *environment_file
    build:
      context: nlp-tools/
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
  db:
    image: 'postgres:latest'
    restart: always
    env_file: # The location we use to share all of our secrets
      - .env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  backend:
    image: 'docker.pkg.github.com/umass-rescue/596-s22-backend/backend:latest'
    depends_on:
      - db
    volumes:
      - ./be-data/:/backend/
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - 8000:8000